my_app/catalog/views.py
from flask import request, jsonify, Blueprint
from my_app import db
from my_app.catalog.models import Product, Category
# from my_app.catalog.models import Product
from decimal import Decimal
from my_app import redis
from flask import render_template
from flask import flash, redirect, url_for
from sqlalchemy.orm.util import join
from my_app.catalog.models import ProductForm, CategoryForm

import os
from werkzeug import secure_filename
from my_app import ALLOWED_EXTENSIONS, UPLOAD_FOLDER


catalog = Blueprint('catalog', __name__)

from functools import wraps

def template_or_json(template=None):
    def decorated(f):
        @wraps(f)
        def decorated_fn(*args, **kwargs):
            ctx = f(*args, **kwargs)
            if request.is_xhr or not template:
                return jsonify(ctx)
            else:
                return render_template(template, **ctx)
        
        return decorated_fn
    return decorated

@catalog.route('/2')
@catalog.route('/home2')
@template_or_json('home.html')
def home():
    # return "Welcome to the Catalog Home."
    products = Product.query.all()
    return dict(count=len(products))
    # if request.is_xhr:
    #     products = Product.query.all()
    #     return jsonify({
    #         'count': len(products)
    #     })
    # return render_template('home.html')

@catalog.route('/product/<id>')
def product(id):
    # product = Product.objects.get_or_404(key=key)
    product = Product.query.get_or_404(id)
    # return 'Product - %s, $%s' % (product.name, product.price)
    return render_template('product.html', product=product)

@catalog.route('/products')
@catalog.route('/products/<int:page>')
def products(page=1):
    products = Product.query.paginate(page, 10)
    return render_template('products.html', products=products)


# @catalog.route('/products')
# def products():
#     products = Product.objects.all()
#     res = {}
#     for product in products:
#         res[product.key] = {
#             'name': product.name,
#             'price': str(product.price),
#         }
#     return jsonify(res)

# @catalog.route('/products')
# def products():
#     products = Product.query.all()
#     res = {}
#     for product in products:
#         res[product.id] = {
#             'name': product.name,
#             'price': str(product.price),
#             'category': product.category.name,
#         }
#     return jsonify(res)

# @catalog.route('/product-create', methods=['POST',])
# def create_product():
#     name = request.form.get('name')
#     key = request.form.get('key')
#     price = request.form.get('price')
#     product = Product(
#                        name = name,
#         key = key,
#         price = Decimal(price)
#     )
#     product.save()
#     return 'Product created.'

def allowed_file(filename):
    return '.' in filename and filename.lower().rsplit('.', 1)[1] in ALLOWED_EXTENSIONS

from werkzeug.datastructures import CombinedMultiDict

@catalog.route('/product-create', methods=['POST','GET'])
def create_product():
    # form = ProductForm(CombinedMultiDict([request.form, request.files]), csrf_enabled=False)
    form = ProductForm(CombinedMultiDict([request.form, request.files]))
    # categories = [(c.id, c.name) for c in Category.query.all()]
    # form.category.choices = categories

    # if request.method == 'POST' and form.validate():
    # flash("%s" % form.name.data, "success")
    # flash("%s" % form.price.data, "success")
    # flash("%s" % form.category.data, "success")
    # flash("%s" % form.image.data, "success")
    if form.validate_on_submit():
        name = form.name.data
        price = form.price.data
        category = Category.query.get_or_404(
            form.category.data
        )
        # name = request.form.get('name')
        # price = request.form.get('price')
        # categ_name = request.form.get('category')
        # category = Category.query.filter_by(name=categ_name).first()
        # if not category:
        #     category = Category(categ_name)
        ###
        image = form.image.data
        if allowed_file(image.filename):
            filename = secure_filename(image.filename)
            image.save(os.path.join(UPLOAD_FOLDER, filename))

        product = Product(name, price, category, filename)

        db.session.add(product)
        db.session.commit()
        flash('The product %s has been created' % name, 'success')
        return redirect(url_for('catalog.product', id=product.id))
    
    if form.errors:
        flash(form.errors, 'danger')

    return render_template('product-create.html', form=form)

@catalog.route('/product-search')
@catalog.route('/product-search/<int:page>')
def product_search(page=1):
    name = request.args.get('name')
    price = request.args.get('price')
    company = request.args.get('company')
    category = request.args.get('category')
    products = Product.query
    if name:
        products = products.filter(Product.name.like('%'+name+'%'))
    if price:
        products = products.filter(Product.price == price)
    if company:
        products = products.filter(Product.company.like('%'+company+'%'))
    if category:
        products = products.select_from(join(Product, Category)).filter(Category.name.like('%'+category+'%'))
    return render_template('products.html', products=products.paginate(page, 10))



@catalog.route('/category/<id>')
def category(id):
    category = Category.query.get_or_404(id)
    return render_template('category.html', category=category)

@catalog.route('/categories')
def categories():
    categories = Category.query.all()
    return render_template('categories.html', categories=categories)


@catalog.route('/category-create', methods=['POST', 'GET'])
def create_category():
    form = CategoryForm(csrf_enabled=False)
    if form.validate_on_submit():
        name = form.name.data
        # name = request.form.get('name')

        category = Category(name)
        db.session.add(category)
        db.session.commit()
        flash('The category %s has been created' % name, 'success')
        return redirect(url_for('catalog.category', id=category.id))

    if form.errors:
        flash(form.errors, "danger")
    # return 'Category created.'
    return render_template('category-create.html', form=form)


from flask_restful import Resource
from my_app import api
from flask import abort
import json
from flask_restful import reqparse
parser = reqparse.RequestParser()
parser.add_argument('name', type=str)
parser.add_argument('price', type=float)
parser.add_argument('category', type=dict)

class ProductApi(Resource):
    def get(self, id=None, page=1):
        # Return product data
        # return 'This is a GET response'
        if not id:
            products = Product.query.paginate(page, 10).items
        else:
            products = [Product.query.get(id)]
        
        if not products:
            abort(404)
        res = {}
        for product in products:
            res[product.id] = {
                'name': product.name,
                'price': product.price,
                'category': product.category.name
            }
        return json.dumps(res)

    def post(self):
        # Create a new product
        # return 'This is a POST response'
        args = parser.parse_args()
        name = args['name']
        price = args['price']
        categ_name = args['category']['name']
        category = Category.query.filter_by(name=categ_name).first()
        if not category:
            category = Category(categ_name)
        product = Product(name, price, category, "iphone6.PNG")
        db.session.add(product)
        db.session.commit()
        res = {}
        res[product.id] = {
            'name': product.name,
            'price': product.price,
            'category': product.category.name,
        }
        return json.dumps(res)

    def put(self, id):
        # Update the product with given id
        # return 'This is a PUT response'
        args = parser.parse_args()
        name = args['name']
        price = args['price']
        categ_name = args['category']['name']
        category = Category.query.filter_by(name=categ_name).first()
        Product.query.filter_by(id=id).update({
            'name': name,
            'price': price,
            'category_id': category.id,
        })
        db.session.commit()
        product = Product.query.get_or_404(id)
        res = {}
        res[product.id] = {
            'name': product.name,
            'price': product.price,
            'category': product.category.name,
        }
        return json.dumps(res)

    def delete(self, id):
        # Delete the product with given id
        # return 'This is a DELETE response'
        product = Product.query.filter_by(id=id)
        product.delete()
        db.session.commit()
        return json.dumps({'response': 'Success'})

api.add_resource(ProductApi
    ,'/api/product'
    , '/api/product/<int:id>'
    , '/api/product/<int:id>/<int:page>'
    )

my_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}" />
        <title>Flask Framework Cookbook</title>
        <link href="{{url_for('static', filename='css/bootstrap.min.css')}}" rel='stylesheet'>
        <link href="{{url_for('static', filename='css/main.css')}}" rel='stylesheet'>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{{url_for('catalog.home')}}">Flask Cookbook</a>
                </div>
            </div>
        </div>
        <div class="container">
            <br/>
            <div>
                {% for category, message in get_flashed_messages(with_categories=true) %}
                <div class="alert alert-{{category}} alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    {{ message }}
                </div>
                {% endfor %}
            </div>

            {% block container %}{% endblock %}
        </div>
        <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.1.1.min.js"></script>
        <script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
        <script src="{{url_for('static', filename='js/moment.min.js')}}"></script>
        {% block scripts %}
        {% endblock %}
    </body>
</html>

my_app/templates/categories.html
{% extends 'home.html' %}

{% block container %}
    <div class="top-pad">
        {% for category in categories %}
            <a href="{{ url_for('catalog.category', id=category.id) }}">
                <h2>{{ category.name }}</h2>
            </a>
        {% endfor %}
    </div>
{% endblock %}

my_app/templates/category-create.html
{% extends 'home.html' %}

{% block container %}
    <div class="top-pad">
        <form method="POST" action="{{ url_for('catalog.create_category')}}" role="form">
            <div class="form-group">{{ form.name.label }}: {{ form.name() }}</div>
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    </div>
{% endblock %}

my_app/templates/category.html
{% extends 'home.html' %}

{% block container %}
    <div class="top-pad">
        <h2>{{ category.name }}</h2>
    </div>
{% endblock %}

my_app/templates/home.html
{% extends 'base.html' %}

{% block container %}
    <h1>Welcome to the Authentication Domo</h1>
    {% if current_user.is_authenticated %}
        <h3>Hey {{ current_user.username }}!!!</h3>
        <a href="{{ url_for('auth.logout') }}">Click here to logout</a>
    {% else %}
        Click here to <a href="{{ url_for('auth.login') }}">login</a> or <a href="{{ url_for('auth.register') }}">register</a>
    {% endif %}
    <!-- <a href="{{url_for('catalog.products')}}" id="catalog_link">Click here to see the catalog</a> -->
{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function(){
            // var csrfToken = $('meta[name="csrf-token"]').attr('content');
            // $.ajaxSetup({
            //     beforeSend: function(xhr, settings){
            //         if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)){
            //             xhr.setRequestHeader("X-CSRFToken", csrfToken);
            //         }
            //     }
            // });
            $.getJSON("/home", function(data) {
                $('#catalog_link').append('<span class="badge">'+data.count+'</span>');
            });
        });
    </script>
{% endblock %}

my_app/templates/login.html
{% extends 'home.html' %}

{% block container %}
    <div class="top-pad">
        <form
            method="POST"
            action="{{ url_for('auth.login') }}"
            role="form">
            {{ form.csrf_token }}
            <div class="form-group">{{ form.username.label }}: {{form.username() }}</div>
            <div class="form-group">{{ form.password.label }}: {{form.password() }}</div>
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    </div>
{% endblock %}

my_app/templates/product-create.html
{% extends 'home.html' %}

{% block container %}
    <div class="top-pad">
        <form action="{{ url_for('catalog.create_product')}}"  method="POST" enctype="multipart/form-data">
            {{ form.csrf_token }}
            <div class="form-group">{{ form.name.label }}: {{ form.name() }}</div>
            <div class="form-group">{{ form.price.label }}: {{ form.price() }}</div>
            <div class="form-group">{{ form.category.label }}: {{ form.category() }}</div>
            <div class="form-group">{{ form.image.label }}: {{ form.image(style='display:inline;') }}</div>
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    </div>
{% endblock %}

my_app/templates/product.html
{% extends 'home.html' %}

{% block container %}
    <div class="top-pad">
        <img src="{{ url_for('static', filename='uploads/'+product.image_path) }}" />
        <h1>{{product.name}} <small>{{product.category.name}}</small></h1>
        <h3>{{product.price}}</h3>
    </div>
{% endblock %}

my_app/templates/products.html
{% extends 'home.html' %}

{% block container %}
    <div class="top-pad">
        {% for product in products.items %}
            <div class="well">
                <h2>
                    <a href="{{url_for('catalog.product',id=product.id)}}">{{product.name}}</a>
                    <small>$ {{product.price}}</small>
                </h2>
            </div>
        {% endfor%}

        {% if products.has_prev %}
            <a href="{{url_for(request.endpoint, page=products.prev_num) }}">
                {{"Previous Page"}}
            </a>
        {% else %}
            {{"Previous Page"}}
        {% endif %}

        {% if products.has_next %}
            <a href="{{ url_for(request.endpoint, page=products.next_num) }}">
                {{"Next page"}}
            </a>
        {% else %}
            {{ "Next page" }}
        {% endif %}
    </div>
{% endblock %}

my_app/templates/register.html
{% extends 'home.html' %}

{% block container %}
    <div class="top-pad">
        <form
            method="POST"
            action="{{ url_for('auth.register') }}"
            role="form">
            {{ form.csrf_token }}
            <div class="form-group">{{ form.username.label }}: {{ form.username() }}</div>
            <div class="form-group">{{ form.password.label }}: {{ form.password() }}</div>
            <div class="form-group">{{ form.confirm.label }}: {{ form.confirm() }}</div>
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    </div>
{% endblock %}